config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  devise_for :users

  namespace :api do
    namespace :v0 do

      resources :foods, only: [:index, :show]
    end
  end
  resources :foods, only: [:index, :show]
  resources :eaten_foods, only: [:create, :destroy]

  root to: 'foods#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/eaten_food.rb
class EatenFood < ApplicationRecord
  belongs_to :user
  belongs_to :food
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :eaten_foods
  has_many :users, through: :eaten_foods
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :eaten_foods
    has_many :foods, through: :eaten_foods
end

app/controllers/api/v0/eaten_foods_controller.rb
class Api:V0::EatenFoodsController < ApplicationController
  before_action :authenticate_user!

  def create
    food = Food.find(params[:food_id])
    net_carbs = food.carbs - food.fiber
    current_user.update(daily_net_carbs: current_user.daily_net_carbs + net_carbs)
    redirect_to root_path, notice: "Food added to your daily net carb count."
  end

  def destroy
    eaten_food = current_user.eaten_foods.find(params[:id])
    net_carbs = eaten_food.food.carbs - eaten_food.food.fiber
    current_user.update(daily_net_carbs: current_user.daily_net_carbs - net_carbs)
    eaten_food.destroy
    redirect_to root_path, notice: "Food removed from your daily net carb count."
  end
end

app/controllers/api/v0/foods_controller.rb
class Api::V0::FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = Food.all
    render json: @foods
  end

  def show
    @food = Food.find(params[:id])
    @food.net_carbs = @food.carbs - @food.fiber
    render json: @food
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = []
    if params[:query].present?
      response = fetch_foods_from_api(params[:query])
      @foods = response['foods'] if response && response['foods'].present?
      Rails.logger.debug "Foods from API: #{@foods.inspect}"
    end
  end

  def show
    @food = fetch_food_by_id(params[:id])
    Rails.logger.debug "Food from API: #{@food.inspect}"
  end

  private

  def fetch_food_by_id(id)
    service = FoodDataCentralService.new("mOkTLDSQdNqogTRPY38ukW70o9lR0fH38Afe1wTc")
    response = service.fetch_food_by_id(id)
    food_details = response['foods'].first if response && response['foods'].present?
    construct_food_object(food_details) if food_details
  rescue StandardError => e
    Rails.logger.error "Error fetching food from API: #{e.message}"
    nil
  end

  def construct_food_object(food_details)
    food = OpenStruct.new(
      fdcId: food_details['fdcId'],
      description: food_details['description'],
      publicationDate: food_details['publicationDate'],
      foodNutrients: food_details['foodNutrients']
    )
    food
  end
  
  def fetch_foods_from_api(query)
    service = FoodDataCentralService.new("mOkTLDSQdNqogTRPY38ukW70o9lR0fH38Afe1wTc")
    service.search_food(query)
  rescue StandardError => e
    Rails.logger.error "Error fetching foods from API: #{e.message}"
    []
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]


  def new
    super
  end


  def create
    super
  end


  def edit
    super
  end


  def update
    super
  end

  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.erb
<div class="container">
  <h1 class="mt-5">Search Foods</h1>

  <%= form_with(url: foods_path, method: "get", class: "mt-3") do %>
    <div class="input-group mb-3">
      <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Enter food name" %>
      <div class="input-group-append">
        <%= submit_tag "Search", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

  <div class="mt-3">
    <h2>Search Results:</h2>
    <% @foods.each do |food| %>
      <%= link_to food['description'], food_path(food['fdcId']) %><br>
    <% end %>
  </div>
</div>

app/views/foods/show.html.erb
<div class="container">
  <h2 class="mt-5">Food Details</h2>

  <% if @food.present? %>
    <div class="card mt-3">
      <div class="card-body">
        <h3 class="card-title"><%= @food.description %></h3>
        <p class="card-text">Publication Date: <%= @food.publicationDate %></p>
        
        <h4>Nutrients (per serving size):</h4>
        <% @food.foodNutrients.each do |nutrient| %>
          <p class="card-text"><strong><%= nutrient.nutrient.name %>:</strong> <%= nutrient.amount %> <%= nutrient.nutrient.unitName %></p>
        <% end %>
      </div>
    </div>
  <% else %>
    <p>No food selected</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Keto Counter</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Include Bootstrap CSS -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <!-- Brand/logo -->
    <a class="navbar-brand" href="#"><%= link_to "Keto Counter", root_path, class: "navbar-brand" %></a>

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <span class="nav-link">
            <% if user_signed_in? %>
              Daily Net Carbs: <%= current_user.daily_net_carbs %> grams
            <% else %>
              Please sign in
            <% end %>
          </span>
        </li>
      </ul>
    </div>
  </div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
  <%= yield %>
</div>

<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</body>
</html>